export const FETCH_PRODUCT_BY_ASIN = 'FETCH_PRODUCT_BY_ASIN';
export const FETCH_PRODUCT_REQUEST = 'FETCH_AVAILABLE_MEALS_REQUEST';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE';